DROP TABLE IF EXISTS Players;
DROP TABLE IF EXISTS NetWorths;
DROP TABLE IF EXISTS Feedbacks;
DROP TABLE IF EXISTS Bounties;
DROP TABLE IF EXISTS Factions;
DROP TABLE IF EXISTS Reputation;
DROP TABLE IF EXISTS LoanedShips;
DROP TABLE IF EXISTS PlayerDebt;

CREATE TABLE IF NOT EXISTS "main"."Players"
(
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE DEFAULT 1, 
    "Name" VARCHAR UNIQUE, 
    "JoinDate" DATETIME,
    "LastLoggedInDate" DATETIME,
    "LastLoggedOutDate" DATETIME,
    "IsAdmin" BOOL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "main"."NetWorths"
(
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE DEFAULT 1,
    "PlayerId" INTEGER UNIQUE,
    "Value" INTEGER NOT NULL DEFAULT 0,
    "LastUpdatedDate" DATETIME
);

CREATE TABLE IF NOT EXISTS "main"."Feedbacks"
(
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE DEFAULT 1,
    "PlayerId" INTEGER,
    "FeedbackDate" DATETIME,
    "Rating" INTEGER,
    "Details" VARCHAR
);

CREATE TABLE IF NOT EXISTS "main"."Bounties"
(
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE DEFAULT 1,
    "TargetPlayerId" INTEGER NOT NULL,
    "PostedDate" DATETIME NOT NULL,
    "Value" INTEGER NOT NULL,
    "ClaimingPlayerId" INTEGER,
    "ClaimedDate" DATETIME
);

CREATE TABLE IF NOT EXISTS "main"."Factions"
(
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE DEFAULT 1,
    "Name" VARCHAR,
    "CreateDate" DATETIME
);

CREATE TABLE IF NOT EXISTS "main"."Reputation"
(
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE DEFAULT 1,
    "PlayerId" INTEGER NOT NULL,
    "FactionId" INTEGER NOT NULL,
    "Reputation" INTEGER NOT NULL DEFAULT 0,
    "UpdatedDate" DATETIME
);

CREATE TABLE IF NOT EXISTS "main"."LoanedShips"
(
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE DEFAULT 1,
    "PlayerId" INTEGER NOT NULL,
    "ShipTemplateName" VARCHAR,
    "ShipName" VARCHAR,
    "Value" INTEGER NOT NULL DEFAULT 0,
    "IsPaid" BOOL NOT NULL DEFAULT 0,
    "UpdatedDate" DATETIME
);

CREATE TABLE IF NOT EXISTS "main"."PlayerDebt"
(
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE DEFAULT 1,
    "PlayerId" INTEGER NOT NULL,
    "Value" INTEGER NOT NULL DEFAULT 0,
    "InterestRate" INTEGER NOT NULL DEFAULT 0,
    "IsPaid" BOOL NOT NULL DEFAULT 0,
    "UpdatedDate" DATETIME
);
